name: thxph - build keebio iris v8 fw

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:

jobs:
  build-keebio-iris-v8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          keyboard: keebio/iris/rev8
          keymap: thxph
          local-keymap-path: keymaps/iris/thxph
          output-dir: qmk-keebio-iris-v8

      - uses: actions/upload-artifact@v4
        with:
          name: keebio-iris-v8-built-images
          path: qmk-keebio-iris-v8
